name: Library Catalog CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code 
      uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install 
    - name: Start BE
      run: npm run start-be &
    - name: Sleep 5 secs
      run: sleep 5
    - name: Start FE
      run: npm run start-fe &
    - name: Sleep 5 secs
      run: sleep 5
    - name: Install browsers
      run: npx playwright install
    - name: UI Tests
      run: npm run test-ui

  deploy_be_app:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build_and_test
    steps:
      - name: Deploy BE app to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_BE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}

  deploy_fe_app:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: deploy_be_app
    steps:
      - name: Deploy FE app to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_FE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
